### ISSUE TITLE
question: psbt output address diff with rgb address

### ISSUE THREAD

**Issue by Matrix-Zhang** [RGB-WG/rgb#115]
1) contruct psbt, the address derive is default to keychain 10 and without taproot tweaks

2) rgb address -k 10 -i index, it derived the address with taproot tweaks

the result is step 1 and step 2 address is not same even though the keychain and index are all same

is this behavior normal?
how to sign the psbt?

**Comment by dr-orlovsky** [comment]
> contruct psbt, the address derive is default to keychain 10 and without taproot tweaks

Nope, it is always with a taproot tweak, since we have to put a tweak into the transaction

> rgb address -k 10 -i index, it derived the address with taproot tweaks

No, this one is WITHOUT taproot tweak, since there is no tweak to apply.

> is this behavior normal?
Yes

> how to sign the psbt?
The normal way - it is outputs which are tweaked, so any signer will work. It is just the  hardware wallets will see the change as an external payments - but there is no way around that until we will have a dedicated RGB app for each of hardware wallets

Overall, it is advised not to use `-k` flag, like in `rgb address -k 10 -i index` unless you are clearly known what you are doing.

Please feel free to re-open if you have any further questions
