### ISSUE TITLE
Exit status incorrect when output reporting error

### ISSUE THREAD

**Issue by yanganto** [RGB-WG/rgb#180]
> moreover, I noticed the exit status of the command is `0` even if the reported error gets output and I think this should be fixed

_Originally posted by @nicbus in https://github.com/RGB-WG/rgb/issues/173#issuecomment-2068833949_

**Comment by yanganto** [comment]
The `exec` of commands, `pay` function of `WalletProvider` return errors.
The current design is really good without bugs, this issue is also possibly out of the scope of this crate, in there we swallow an error and just print it out.

**Comment by nicbus** [comment]
> The exec of commands, pay function of WalletProvider return errors.
> The current design is really good without bugs, this issue is also possibly out of the scope of this crate, in there we swallow an error and just print it out.

I'm having a hard time understanding what you mean, so I'll explain what I think is the issue in more detail.

In my opinion the issue here is that when a non-recoverable error is encountered, the command exits without completing the task it was supposed to, but exits with a zero status code, which means everything went well. This is a problem because a CLI user (or pipeline, or script) then assumes that the command worked and produced the expected results, while this is not the case and further operations down the line will fail because of this.

IMO it's important to report that the command did not produce the expected result by exiting with a non-zero status code, which can be handled by the user (e.g. by checking `$?`) or automatically (e.g. setting the shell's `-e` option).

As a more concrete example, in the original issue the command to create a wallet was the one failing with an error, which means the intended result of the command (creating a wallet) had not been achieved, which is why I think the exit status should have been non-zero. With a zero exit code, the user (or script) continues with the following commands (e.g. trying to generate an address) but they will fail because the wallet is not there.

**Comment by yanganto** [comment]
The `$?` thing is shell operation, I know what you mean.  We do not have a shell (.sh) in the repo.  

This happens when `$rgb something` and an error occurs with successful exit status. This is about the rust program and not about the shell.  Did I misunderstand something?

The main.rs returns an error code if the error is raised.
https://github.com/RGB-WG/rgb/blob/76a227730abb710cdd02f09207c2b36c64d938f6/cli/src/main.rs#L47C1-L47C26

If there is an error report with a successful exit status, it means the system swallows an error somewhere.

**Comment by nicbus** [comment]
> The main.rs returns an error code if the error is raised.
> https://github.com/RGB-WG/rgb/blob/76a227730abb710cdd02f09207c2b36c64d938f6/cli/src/main.rs#L47C1-L47C26

> If there is an error report with a successful exit status, it means the system swallows an error somewhere, because Result is a primary type and can be used for Rust function return, if some error happens and is swallowed it will not pass to the return.

You're right, the exit code was being masked by the fact that some `rgb` commands were executed inside a subshell or pipe. I didn't spot that difference initially, sorry for that, this can be closed.

**Comment by yanganto** [comment]
This can open here if it is not confusing because this reflects the one issue we ran into before and we still have no mitigation.
