### ISSUE TITLE
refactored electrum resolver introduced bug in getting confirmation number

### ISSUE THREAD

**Issue by nicbus** [RGB-WG/rgb#189]
The refactor of the electrum resolver (commit `eeb9d55`) introduces a bug, as `last_block_height_min` is obtained after the call to `blockchain.transaction.get` and `last_block_height_max` is then set to the same value as `last_block_height_min` (making the loop for `height` useless).

This way it's possible that new blocks are found after the call to `blockchain.transaction.get` and thus the number of confirmations would be wrong.

The original implementation set `last_block_height_min` before calling `blockchain.transaction.get` and `last_block_height_max` just before the `height` loop.

**Comment by dr-orlovsky** [comment]
No, both contain the same issue, and the original code relies on the assumption that nothing was changed since the last code. In the refactored code the calls are going one after one and thus the whole loop is unnecessary - and the construction still contains the original issue.

I have re-written the whole approach in https://github.com/RGB-WG/rgb/pull/190/commits/790ba4b18bb8097b0f51953097f51d2965528ec5

**Comment by nicbus** [comment]
Not sure what you meant exactly, as the original logic has been shown to not contain any bugs (except for the particular case reported by Adam, see below) and the refactored one now contains the same logic, including the loop.

Anyway, the matter has been discussed elsewhere and the refactored implementation has been fixed and improved (up to commit `e8ad27a` ATM), in order to handle cases where one or more blocks are found between the `block_headers_subscribe` and `blockchain.transaction.get` calls.

The other possible issue that's been reported by Adam, where the two calls could return inexact results due to asynchronous DB updates, doesn't seem to have been addressed, though.
