### ISSUE TITLE
cli: enable invoice for UDA

### ISSUE THREAD

**Issue by zoedberg** [RGB-WG/rgb#204]
Currently via CLI it's not possible to create an invoice to receive a UDA.

@crisdut could you please take care of this?

**Comment by crisdut** [comment]
> @crisdut could you please take care of this?

Yes!

**Comment by crisdut** [comment]
> @crisdut any news on this?

I'm having a hard time finding the time to do this, but give me a few days and I'll do it.

**Comment by dr-orlovsky** [comment]
The last three commits in https://github.com/RGB-WG/rgb/pull/248 are now do the NFT (and all other forms) of invoicing, closing this issue.

I first tried to do it as a dedicated PR, but it was not possible since I needed a lot of stuff I did in the `develop` branch already, so I just added those things on top.
