### ISSUE TITLE
Examples for create/import wallet with v0.11

### ISSUE THREAD

**Issue by oneforalone** [RGB-WG/rgb#45]
I'm trying to use the latest version(i.e master/v0.11) to create a wallet, however, got an error with `unknown username 'DCSgjFcLS9iZkN6H4BxuhUga'`. Here is the command i run:

```shell
./rgb create alice --tapret-key-only tapret(tpubDCSgjFcLS9iZkN6H4BxuhUgabTchh3qqad49fYqndF595dnhcVTApsaEfGXXMVJTh2wrT2wKWPbcrSaX6VNMSaBp8NYThxHj3DA8oDiUNcK)
```

Also, i found that in the source codes, there're `bp.toml` and `rgb.toml` configuration files. Is there some examples for these two configure file, i.e. What fields can i set in these two file?

**Comment by dr-orlovsky** [comment]
You misspel the descriptor. Instead of `tapret(tpubDCSgjFcLS9iZkN6H4BxuhUgabTchh3qqad49fYqndF595dnhcVTApsaEfGXXMVJTh2wrT2wKWPbcrSaX6VNMSaBp8NYThxHj3DA8oDiUNcK)` it should be `[master_fingerprint/86h/1h/0h]/tpubDCSgjFcLS9iZkN6H4BxuhUgabTchh3qqad49fYqndF595dnhcVTApsaEfGXXMVJTh2wrT2wKWPbcrSaX6VNMSaBp8NYThxHj3DA8oDiUNcK/<0;1;9;10>/*` where `master_fingerprint` must be replaced with the seed master fingerprint as a hexadecimal 8 chars.

**Comment by shuimuliang** [comment]
e.g:
``` sh
rgb create -d .alice default \
  --tapret-key-only  "[64cb48ea/84h/0h/0h]xpub6DAHwd8k5Vq32trU8BJ1dPGLgYeCs8VLUNrkve574pSaWPjD5VC8tyKrfFeopZUt1jxVC2noDzWtyvsugVrHyR3XnD7Srbxnc5XECzc2Pqv/<0;1>/*"
```

**Comment by shuimuliang** [comment]
It has been resolved.
Please close this issue too.
