### ISSUE TITLE
Wrong MAGIC Number in PSBT (transfer step)

### ISSUE THREAD

**Issue by crisdut** [RGB-WG/rgb#71]
### **Description**
**Version:** https://github.com/RGB-WG/rgb/pull/39/commits/62b5009146b363553493e2a3a9b516866f54c78c

I noticed the wrong behavior in `Psbt::encode` in the transfer step.

For some reason, when I try to sign the PSBT created in the transfer step, the `descriptor-wallet` returns:

```
Magic bytes for a PSBT must be the ASCII for "PSBT" serialized in the most significant byte order.
```

But, this problem does not occur when I try to sing the PSBT created by the command `rgb construct ...`.

**Comment by dr-orlovsky** [comment]
Can't confirm: I was able to sucessfully sign the generated PSBT with descriptor wallet - https://mempool.space/testnet/tx/98ea384abd8ec9d13244689ab76db59264311c8b1de4944a72a789d6108ac035

I think you copied Base64 PSBT representation from console, saved to file and tried to sign - and that would not work (since the file must be binary). Just add PSBT filename at the end of `transfer` command args and it will save a binary version to it such that you can sign
